local white = Color( 255, 255, 255, 255 )

killicon.Add( "cw_ak74", "hud/killicons/ak74", white )
killicon.Add( "cw_ar15", "hud/killicons/ar15", white )
killicon.Add( "cw_deagle", "hud/killicons/deagle", white )
killicon.Add( "cw_flash_thrown", "hud/killicons/flash_grenade", white )
killicon.Add( "cw_grenade_thrown", "hud/killicons/frag_grenade", white )
killicon.Add( "cw_g3a3", "hud/killicons/g3a3", white )
killicon.Add( "cw_l115", "hud/killicons/l115", white )
killicon.Add( "cw_mp5", "hud/killicons/mp5", white )
killicon.Add( "cw_mr96", "hud/killicons/mr96", white )
killicon.Add( "cw_smoke_thrown", "hud/killicons/smoke_grenade", white )
killicon.Add( "cw_fiveseven", "hud/killicons/fiveseven", white )
killicon.Add( "cw_g36c", "hud/killicons/g36c", white )
killicon.Add( "cw_l85a2", "hud/killicons/l85a2", white )
killicon.Add( "cw_m3super90", "hud/killicons/m3super90", white )
killicon.Add( "cw_m14", "hud/killicons/m14", white )
killicon.Add( "cw_m249_official", "hud/killicons/m249", white )
killicon.Add( "cw_m1911", "hud/killicons/m1911", white )
killicon.Add( "cw_mac11", "hud/killicons/mac11", white )
killicon.Add( "cw_makarov", "hud/killicons/makarov", white )
killicon.Add( "cw_p99", "hud/killicons/p99", white )
killicon.Add( "cw_scarh", "hud/killicons/scarh", white )
killicon.Add( "cw_shorty", "hud/killicons/shorty", white )
killicon.Add( "cw_ump45", "hud/killicons/ump45", white )
killicon.Add( "cw_vss", "hud/killicons/vss", white )
killicon.Add( "cw_famasg2_official", "hud/killicons/famas", white )
killicon.Add( "cw_mp7_official", "hud/killicons/mp7", white )
killicon.Add( "cw_xm1014_official", "hud/killicons/m1014", white )
killicon.Add( "cw_mp9_official", "hud/killicons/mp9", white )
killicon.Add( "cw_saiga12k_official", "hud/killicons/saiga", white )
killicon.Add( "cw_svd_official", "hud/killicons/svd", white )
killicon.Add( "cw_akm_official", "hud/killicons/akm", white )

